.github/workflows/publish.yml, Makefile
Closes #102 
This allows us to have per release a default manifest that users can install through:
```
kubectl apply -f https://github.com/spotify/flink-on-k8s-operator/releases/download/$VERSION/flink-operator.yaml
```
instead of requiring `make deploy`
=> Add CI release manifest step

controllers/flinkcluster_submit_job_script.go
When deploying a new cluster, the submitter is hanging by `curl -sS "http://jobmanager:8081/jobs"` for a long time until the default timeout of 120s because the jobmanager is not yet ready.
Adding `--connect-timeout <seconds>` to solve this problem.
=> Add connection timeout to job submitter script

controllers/flinkcluster_util.go
When running with injected sidecars (i.e. istio-proxy) pod.GetLogs requires a container name to be specified.
From https://pkg.go.dev/k8s.io/api/core/v1#PodLogOptions:
```go
type PodLogOptions struct {
metav1.TypeMeta `json:",inline"`
// The container for which to stream logs. Defaults to only container if there is one container in the pod.
// +optional
Container string `json:"container,omitempty" protobuf:"bytes,1,opt,name=container"`
```
=> specify container name "main" to account for sidecar containers

config/samples/flinkoperator_v1beta1_flinkjobcluster.yaml, config/samples/flinkoperator_v1beta1_flinkjobcluster_volcano.yaml, config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml, config/samples/flinkoperator_v1beta1_flinksessioncluster_volcano.yaml
The current samples can't submit successfully because the memory exceeded the default limitation.
So that I increased the resources to make the samples can submit and run successfully.
=> Samples: Increase the resources so that the examples can run successfully

README.md
After we upgraded the CRDs, K8s 1.16 is required
=> docs: Fix prerequisites

controllers/flinkcluster/batchscheduler/volcano/volcano.go
This will most likely mean that the PodGroup was deleted or it was never
created. In either case we don't want to fail the reconcile loop.
=> Avoid throwing on PodGroup deletion when NotFound

controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_converter_test.go
This commit mounts the whole flinkConfigMapVolume to /opt/flink/conf at the job-submitter
=> Mount log conf to job-submitter

controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_converter_test.go, controllers/flinkcluster/flinkcluster_util.go
When needed these should be set by the user, reducing the level of
"magic" things happening in the operator and keeps it inline with k8s
philosophy.
=> Revert setting Jar/Py files env vars

docs/python_guide.md
* Updated references to 'pythonFile', 'pythonFiles', and 'pythonModule' to 'pyFiles' etc as this is the current CRD API spec
* Added reference to the Python Dockerfile provided
* General clean up of the documentation
=> Update pyFlink documentation 

helm-chart/flink-operator/templates/flink-operator.yaml, helm-chart/flink-operator/templates/generate-cert.yaml, helm-chart/flink-operator/templates/serviceaccount.yaml, helm-chart/flink-operator/update_template.sh, helm-chart/flink-operator/values.yaml
In this PR, I fixed multiple issues I stumbled across when I was trying to deploy this project:
* Fix for ignoring watchNamespace
* Fix for creating SA in proper namespace, without it, replicaset won't be able to create any operator replicas, due to error of finding SA
* Fix for mounting secret "cert" as volume, without using proper SA name, it won't be able to find it even if it's in a correct NS
* Little grammar fix
=> Implement multiple Helm chart fixes

config/samples/flinkoperator_v1beta1_flinkjobcluster.yaml
I found `flinkoperator_v1beta1_flinkjobcluster.yaml` and `flinkoperator_v1beta1_remotejobjar.yaml` missed required fields for v1beta1 `flinkclusters.flinkoperator.k8s.io`.
=> Add required fields to job cluster samples

apis/flinkcluster/v1beta1/flinkcluster_types.go, apis/flinkcluster/v1beta1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_converter_test.go, helm-chart/flink-operator/templates/flink-cluster-crd.yaml
Issue ref: https://github.com/spotify/flink-on-k8s-operator/issues/319
Result of patch:
* Changes to example cluster:
```
jobManager:
+    accessScope: External
+    ServiceAnnotations:
+      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
* Describe output from service:
```
$ kubectl describe svc flink-illiatest-jobmanager -n flink-job
Name:                     flink-illiatest-jobmanager
Namespace:                flink-job
Labels:                   app=flink
cluster=flink-illiatest
component=jobmanager
flinkoperator.k8s.io/revision-name=flink-illiatest-67bd68c554
Annotations:              service.beta.kubernetes.io/aws-load-balancer-internal: true
```
Image I built to test feature: https://hub.docker.com/repository/docker/sudokamikaze/flinktests built on latest master …
=> Add ability to add annotations and labels to JobManager service

docs/crd.md
Missing in https://github.com/spotify/flink-on-k8s-operator/pull/320
=> Update CRD documentation to reflect ServiceLabels and ServiceAnnotations

helm-chart/flink-operator/templates/flink-operator.yaml, helm-chart/flink-operator/values.yaml
Hi there, 
thanks a lot for providing and keeping up to date this fork. I would like to contribute this small PR to: 
- incorporate `imagePullPolicy` for the operatorImage at flink-operator.yaml  (it was setup by never used)
- allow the possibility to specify RBAC proxy docker image as templating so that custom artifactory/mirrors can also be attached to it
- Revert back the watch namespace to be empty for default values
Best regards, 
Gezim
=> Move out the RBAC proxy image as templating value

examples/beam/with_job_server/beam_flink_cluster.yaml, examples/beam/without_job_server/beam_flink_cluster.yaml
Existing yaml files fails because of missing flinkVersion and resources cpu limit not defined.
Add required spec.flinkVersion
Remove resources so that default values will be used
=> Update beam example cluster yaml

.github/workflows/release-helm-charts.yaml
Hi everyone, 
I do understand that the helm-chart release should also be official under the operator name/domain but sometimes it is really hard to keep sync/install it from sources when you also want to keep in sync with the latest changes of the chart or even to extreme install it e.g. on GKE via terraform -- as such you have to install it into some registry which is then able to be used are repo.
To really get rid of all those manual steps I did test this workflow with [one demo example](https://github.com/GezimSejdiu/helm-chart-releaser-demo) and it seems to work out-of the box thanks to https://github.com/helm/chart-releaser-action.
So instad of installing it from sources (I didnt' update the documentation yet, but I can also do it when this goes through so that we also adapt them …
=> Add release helm charts workflow

controllers/flinkcluster/flinkcluster_submit_job_script.go
in case user forgets to execute the pipeline, the logs are not informative. warn users more explicitly in this case
=> log when the submitter ends with success but no job id

controllers/flinkcluster/flinkcluster_observer.go
We are running a job with 600 replicas. Unlike other logs, this one grows with replica count. It started breaking our GCP structured logging. Can we log count instead of all items?
=> reduce pvc list logging

internal/util/kube.go
Unclear why the selector was dropped in this commit: https://github.com/spotify/flink-on-k8s-operator/commit/ffd9ec7cdad8370662847223b4cc4b2b91154433
=> fixes #392, select "main" container for logs

controllers/flinkcluster/flinkcluster_observer.go
if a JM responds to both GetJobsOverview and GetJobExceptions successfully or exceptionally, it continues running. But if it responds to GetJobsOverview and then fails at GetJobExceptions, it is marked as Lost and then stopped.
This commit reorders related statements to prevent this behaviour.
=> fix busy but healthy job from getting lost

controllers/flinkcluster/flinkcluster_controller.go, controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_observer.go, controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_util.go, controllers/flinkcluster/flinkcluster_util_test.go, internal/model/model.go
To enable `jobmanager.retrieve-taskmanager-hostname: "true"` and allow faster recovery of lost TMs,  a headless service has to be created for the pods of the TM statefulset. 
This is not created automatically, when the statefulset is created: See more at https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id
=> Add Headless service for TaskManagers

controllers/flinkcluster/flinkcluster_converter.go
If the defaulting webhook fails for some reason, this check will ensure that the desired state uses 
`deploymentType: StatefulSet`
cc: @jto
=> DeploymentType should be StatefulSet if defaulting webhook fails

internal/batchscheduler/volcano/volcano.go, internal/batchscheduler/volcano/volcano_test.go
- Storage is part of the pod spec and was missed in calculating Deployment resources for volcano's podGroup.
=> Add storage to deployment resource calculation for podGroup

apis/flinkcluster/v1beta1/flinkcluster_types.go, apis/flinkcluster/v1beta1/flinkcluster_types_util.go, apis/flinkcluster/v1beta1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_observer.go, controllers/flinkcluster/flinkcluster_submit_job_script.go, controllers/flinkcluster/flinkcluster_updater.go, docs/crd.md
Fixes #424 
- Job submitter script swallows the job exit code. It should just forward it.
- The exit code of the submitter should be made available in the FlinkCluster Status
- JobState should be marked as Failed if the submitter exit code is not zero.[ This commit](https://github.com/spotify/flink-on-k8s-operator/pull/425/commits/4eb671b49500a143092d088acead12b6e53772b1) tries to make this happen. Do we need this? 🤔
=> Forward submitter exitcode to FlinkCluster status

apis/flinkcluster/v1beta1/flinkcluster_types.go, apis/flinkcluster/v1beta1/flinkcluster_types_util.go, controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_updater.go
Old clusters are stuck in re-queuing.
See discussion here: https://github.com/spotify/flink-on-k8s-operator/pull/425
=> Revert jobsubmitterfailed status and keep exitCode field

controllers/flinkcluster/flinkcluster_reconciler.go
There can be things that need to execute in the `main` after the flink job. Currently, the cluster can be torn down before that happens (it is a race condition).
=> Wait for submitter to exit before tearing down

controllers/flinkcluster/flinkcluster_converter.go, controllers/flinkcluster/flinkcluster_converter_test.go
This commit adds labels to ephemeral volumeClaimTemplate, so same labels are used at both statefulSet or deployment pvcs.
=> use same pvc labels for tm deployment mode as statefulSet mode

apis/flinkcluster/v1beta1/flinkcluster_validate.go
In has finished or was already cancelled, the validation webhook rejects the cancellation attempt. This leads to any external system (ie. Flyte) attempting to continuously retrying the cancellation to reconcile its state.
=> Noop on attempt to cancel non-running job

controllers/flinkcluster/flinkcluster_observer.go
Fixes issue happening with certain streaming clusters:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x468 pc=0x13e1cc5]
goroutine 551 [running]:
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*FlinkJobSubmitter).getState(...)
/workspace/controllers/flinkcluster/flinkcluster_observer.go:115
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*ClusterStatusUpdater).deriveJobStatus(0xc053113898)
/workspace/controllers/flinkcluster/flinkcluster_updater.go:664 +0x8c5
...
```
=> Fix job submitter status nil pointer access

apis/flinkcluster/v1beta1/flinkcluster_default.go, controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_updater.go, controllers/flinkcluster/flinkcluster_util.go
Fixes #434 
+
- control status requested should only be updated at the first reconcile (and not every reconcile). To keep track of when the control was actually requested.
- Reasonable amount of time can then be computed from when the control was requested.
=> job-cancel control should tear down the cluster within a reasonable amount of time

controllers/flinkcluster/flinkcluster_updater.go
The failure reason is set later in the code. Setting it here actually causes an issue bc. the exceptions are not added to failureReasons if failureReasons already contains something. On top of that, the function `deriveJobSubmitterExitCodeAndReason` returns the first few lines of  the submitter logs (up to 4096 chars), which generally are unhelpful.
=> Fix failure reason

controllers/flinkcluster/flinkcluster_controller.go, controllers/flinkcluster/flinkcluster_observer.go
With this commit, an event will be send when a FLinkCluster is detected to be deleted.
=> send an event when the cluster is deleted

apis/flinkcluster/v1beta1/assets/test/flinkcluster_type_fetched.yaml, apis/flinkcluster/v1beta1/assets/test/flinkcluster_type_test.yaml, apis/flinkcluster/v1beta1/flinkcluster_default.go, apis/flinkcluster/v1beta1/flinkcluster_default_test.go, apis/flinkcluster/v1beta1/flinkcluster_types.go, apis/flinkcluster/v1beta1/flinkcluster_types_test.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster/flinkcluster_util_test.go, controllers/flinkcluster/suite_test.go
Introduce kubebuilder markers for types.
Advantages:
* Reduces webhook code writing (default/validating)
* Improve readability
* Leverage k8s API server and reduce operator custom webhook dependece.
* Make local development easier (reduce manifest writing for default values (related to local deployment issues of webhooks)
=> Introduce kubebuilder markers for type validation/defaulting

Makefile, controllers/flinkcluster/flinkcluster_controller_test.go, controllers/flinkcluster/flinkcluster_converter_test.go, controllers/flinkcluster/suite_test.go
Currently, we don't have any controller tests. 
To add more functionality(more CRDs?) safely, we should have a framework for adding FlinkCluster lifecycle tests. 
- Use explicit envtest versions
- Test to check if JobManager StatefulSet exists on new FlinkCluster creation
=> Controller tests setup

apis/flinkcluster/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster/flinkcluster_util_test.go
The change to ommit the `RestartPolicy` when not set (introduce in #449) results in null not be included in the json serialization resulting in different revision number causing Stopped clusters to Update.
We should `ommitempty` for `RestartPolicy` but that should be deffered to `v1beta2`
=> Fix: RestartPolicy serde results in different revision

apis/flinkcluster/v1beta1/flinkcluster_default.go, controllers/flinkcluster/flinkcluster_controller_test.go, controllers/flinkcluster/flinkcluster_converter_test.go, controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_util.go
If a `job-cancel` is requested, 
- the job can immediately be cancelled.
- after that, the submitter job can also be killed.
- New controller tests for testing cancellation scenario.
- minor dummyFlinkCluster fixes in existing tests.
- `s/flinkjobcluster-sample/fjc/g`
- `s/FOOMAP/foomap/g`
=> Job cancellation refactor and more controller tests

apis/flinkcluster/v1beta1/flinkcluster_types.go, apis/flinkcluster/v1beta1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster/flinkcluster_controller_test.go, controllers/flinkcluster/flinkcluster_converter.go
This is a breaking change as the PDB will no longer be added by default.
If you rely on PDB make sure you define it in the CRD.
Fixes #487
=> Make PodDisruptionBudget optional

apis/flinkcluster/v1beta1/flinkcluster_validate.go
While trying to apply the job-cancel annotation in a `FlinkCluster` which has a `Job` spec defined and `job.savepointsDir` undefined, the request is rejected with:
```
updating job is not allowed when spec.job.savepointsDir was not provided
```
This PR aims to fix this ☝️  bug.
=> Skip validation when job-cancel control applied

apis/flinkcluster/v1beta1/flinkcluster_validate.go
Follow up to #610. This PR is addressing deprecated spec prop to request job cancellation.
=> Follow-up to #610: don't skip validation if cancel request is used

controllers/flinkcluster/flinkcluster_updater.go
In an edge case, the job can succeed but exit code remains -1.
- The operator is down or restarted and busy with reconciling all clusters.
- The jobsubmitter pod is cleaned up externally, by kube-system:pod-garbage-collector
In this case, we lose job submitter pod and exit code. But since job status is `Succeeded`, we know exit code should have been 0.
=> Fix: Replace exit code if the job succeeds

controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_updater.go, controllers/flinkcluster/flinkcluster_util.go
Fixes https://github.com/spotify/flink-on-k8s-operator/issues/709
- I am not sure if there is any benefit from setting the status to `Restarting`, so removed it. It shouldn't be `updater`'s responsibility to change desired state.
- In cases of Deploy failed, the status kept looping between: `Restarting` > `Deploying` > `Failed` > `Restarting`. I believe the `reconciler` should look at a Failed job and decide to respawn a new one.
=> Make sure application mode clusters aren't stuck in status updating

controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_updater.go, controllers/flinkcluster/flinkcluster_util.go
Fixes https://github.com/spotify/flink-on-k8s-operator/issues/711
Flink jobId should not be reset on submitter restart.
A new Flink Job ID on each restart can cause multiple jobs to be submitted after a JobManager restart.
Steps to reproduce:
- Start a job with Application mode and HighAvailability turned on
- rescale the FlinkCluster `kubectl rescale FlinkCluster <fc> --replicas=2`
- Delete jobManager pod
- Multiple jobs can be seen in the jobManager console upon job manager restart.
=> Do not reset Flink job-ID

controllers/flinkcluster/flinkcluster_reconciler.go, controllers/flinkcluster/flinkcluster_updater.go
If the job submitter fails, there is no point in running the job anymore. Kill the job.
Fixes https://github.com/spotify/flink-on-k8s-operator/issues/720
=> if submitter fails, kill the job

main.go
=> Fix: define default namespace cache only if watchNamespace is set
