- Makefile
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
> Downgrade controller-gen to v0.2.4

- controllers/flinkcluster_converter.go
- controllers/flinkcluster_converter_test.go
This fix has a PR upstream ... however, it seems that it might take some time to be addressed. Let's fix it in our fork in the meantime.
> Add wildcard to ingress root path

- Makefile
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
- config/webhook/kustomization.yaml
- config/webhook/manifests.v1beta1.yaml
- config/webhook/patches/admission_cabundle.yaml
> Fix persistent volume claim missing metadata

- controllers/flinkcluster_converter.go
- controllers/flinkcluster_converter_test.go
> Add OwnerReferences to persistent volume claims

- controllers/flinkcluster_updater.go
> Fix cluster state stuck in creating state when there's no running components

- config/rbac/role.yaml
- controllers/flinkcluster_controller.go
- controllers/flinkcluster_converter.go
- controllers/flinkcluster_converter_test.go
- controllers/flinkcluster_observer.go
- controllers/flinkcluster_reconciler.go
> Fix presistent volume claim garbage collection

- controllers/flinkcluster_updater.go
> Fix cluster creating state

- controllers/flinkcluster_submit_job_script.go
> Report job id if failure happens after submission

- controllers/batchscheduler/volcano/volcano_test.go
- controllers/flinkcluster_converter.go
- controllers/flinkcluster_converter_test.go
- images/flink/docker/entrypoint.sh
Request limits are enforced so no need for these.
> Remove cpu/mem envs

- controllers/flinkcluster_submit_job_script.go
> Increase submitter retry time

- api/v1beta1/flinkcluster_types.go
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
- controllers/flinkcluster_observer.go
- controllers/flinkcluster_updater.go
- controllers/flinkcluster_updater_test.go
Fixes #71 
Fixes #72 
Fixes #80
> Add flink job name to job status

- main.go
> Add support for zap logging flags

- api/v1beta1/flinkcluster_types.go
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
> Add more printer columns to provide useful flink type-specific information

- README.md
- docs/developer_guide.md
- docs/user_guide.md
> Update Install/Dev documentation

- config/default/manager_config_patch.yaml
> Set default config logging to production

- controllers/flinkcluster_observer.go
- controllers/flinkcluster_updater.go
> Fix: apply cleanup policy when submitter init containers fail

- config/manager/manager.yaml
- helm-chart/flink-operator/templates/flink-operator.yaml
> Bump operator resource requests and limits

- controllers/flinkcluster_updater.go
> Fix: set FailureReasons when job failed

- controllers/flinkcluster_converter.go
- controllers/flinkcluster_converter_test.go
> Set FlinkCluster resournce as initial PVC OwnerReference

- helm-chart/flink-job-cluster/templates/flinkjobcluster.yaml
- helm-chart/flink-job-cluster/values.yaml
- helm-chart/flink-operator/README.md
- helm-chart/flink-operator/templates/_helpers.tpl
- helm-chart/flink-operator/templates/flink-cluster-crd.yaml
- helm-chart/flink-operator/templates/flink-operator.yaml
- helm-chart/flink-operator/templates/generate-cert.yaml
- helm-chart/flink-operator/templates/rbac.yaml
- helm-chart/flink-operator/templates/serviceaccount.yaml
- helm-chart/flink-operator/values.yaml
- fix the crd validation issue
- fix the force namespace creation issue
- fix the openssl cert for webhook validation
> fix operator helm chart with openssl cert

- Makefile
- docs/config.yaml
- docs/crd.md
> Initial auto-gen CRD docs

- Makefile
- api/v1beta1/flinkcluster_types.go
- docs/crd.md
[crd.md](https://github.com/moonsub-kim/flink-on-k8s-operator/blob/update-comment/docs/crd.md)
> Update CRD comment and generate crd.md

- controllers/flinkcluster_converter.go
- docs/crd.md
- images/flink/Makefile
- images/flink/README.md
- images/flink/docker/Dockerfile
- images/flink/docker/Dockerfile.python
- images/flink/docker/entrypoint.sh
- images/flink/properties
> Download python files from remote location

- apis/flinkcluster/v1beta1/flinkcluster_types_util.go
- controllers/flinkcluster/flinkcluster_updater.go
> Fix: don't set failure reasons when job succeeds or is cancelled

- helm-chart/flink-operator/README.md
> docs: Fix helm cmd

- controllers/flinkcluster/flinkcluster_reconciler.go
- controllers/flinkcluster/flinkcluster_updater.go
> Cancel running jobs through job-cancel control annotation

- apis/flinkcluster/v1beta1/flinkcluster_types.go
- apis/flinkcluster/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
- controllers/flinkcluster/flinkcluster_converter.go
> Add Tolerations and NodeSelector to JobSpec

- apis/flinkcluster/v1beta1/flinkcluster_default.go
- apis/flinkcluster/v1beta1/flinkcluster_default_test.go
> Add Job default resources

- controllers/flinkcluster/flinkcluster_controller.go
- main.go
> Allow setting MaxConcurrentReconciles

- helm-chart/flink-operator/templates/flink-operator.yaml
Fixed https://github.com/spotify/flink-on-k8s-operator/pull/257, sry for that :(
> Fix Helm chart Values path

- controllers/flinkcluster/flinkcluster_reconciler.go
> Fix scheduler queue value property

- internal/batchscheduler/volcano/volcano.go
- internal/batchscheduler/volcano/volcano_test.go
> Rework volcano PodGroup MinResources to reflect limits and requests

- internal/batchscheduler/volcano/volcano.go
- internal/batchscheduler/volcano/volcano_test.go
> Fix: add volume claim resource requirements to volcano podgroups

- config/rbac/role.yaml
- helm-chart/flink-operator/templates/rbac.yaml
> Update Helm rbac rules

- controllers/flinkcluster/flinkcluster_converter.go
> fix #389: fromSavepoint not work at first time

- docs/user_guide.md
- helm-chart/flink-operator/templates/flink-cluster-crd.yaml
Updated Helm CRDs to reflect https://github.com/spotify/flink-on-k8s-operator/commit/ee9d70ab08fd3f0d8eec3863f19bb2d324d47480
Also updated cert-manager to newer version
> Helm CRDs & Docs update 

- apis/flinkcluster/v1beta1/flinkcluster_types_util.go
- apis/flinkcluster/v1beta1/flinkcluster_validate.go
- controllers/flinkcluster/flinkcluster_converter.go
- internal/util/kube.go
- internal/util/kube_test.go
> Respect Request ResourceRequirements

- controllers/flinkcluster/flinkcluster_observer.go
This removes multiple log entries making it easier to inspect i.e when using json format.
> Cleanup observer and improve logging

- apis/flinkcluster/v1beta1/flinkcluster_default.go
This defaults will eventually move to kubebuilder tags as well if possible.
> Fix nil pointer when call Default func

- apis/flinkcluster/v1beta1/flinkcluster_validate.go
- apis/flinkcluster/v1beta1/flinkcluster_validate_test.go
> Fix: validate if cluster names are DNS-1035

- apis/flinkcluster/v1beta1/flinkcluster_types.go
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
> Add new resource short name

- controllers/flinkcluster/flinkcluster_converter.go
- controllers/flinkcluster/flinkcluster_converter_test.go
> Remove Ingress port number as it is mutually exclusive with port name

- .github/workflows/release-helm-charts.yaml
Till this is addressed https://github.com/helm/chart-releaser-action/issues/60
> Use helm/chart-releaser-action fork

- controllers/flinkcluster/flinkcluster_updater.go
Avoid getting the error bellow by getting the latest version of the cluster.
```
the object has been modified; please apply your changes to the latest version and try again
```
> Decrease update status errors

- controllers/flinkcluster/flinkcluster_util.go
> Fix: account for pdb update only if it was set in the cluster spec

- controllers/flinkcluster/flinkcluster_updater.go
We should check other failure conditions only if the savepoint status is a failure.
Fixes #562
> Fix: Savepoint status incorrectly derived after it succeeded

- controllers/flinkcluster/flinkcluster_observer.go
> Fix: avoid mutation of submitter job status reference

- apis/flinkcluster/v1beta1/flinkcluster_validate.go
- apis/flinkcluster/v1beta1/flinkcluster_validate_test.go
> Remove unneeded validation rules due to new CRD validation

- controllers/flinkcluster/flinkcluster_util.go
If job cancel was requested, and there's changes introduced in the spec, don't trigger the update process.
> Fix: isJobUpdate should return false when job cancel was requested

- apis/flinkcluster/v1beta1/flinkcluster_validate.go
Reverts spotify/flink-on-k8s-operator#559
Per my comment @ https://github.com/spotify/flink-on-k8s-operator/pull/559#pullrequestreview-1246447151
> Revert "Skip validation when job-cancel control applied"

- controllers/flinkcluster/flinkcluster_converter.go
- controllers/flinkcluster/flinkcluster_reconciler.go
> Add revision hash labels to PDB and fully reconcile object

- apis/flinkcluster/v1beta1/flinkcluster_types.go
- apis/flinkcluster/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
- controllers/flinkcluster/flinkcluster_converter.go
- docs/crd.md
- added affinity passthrough to pod spec
For issue https://github.com/spotify/flink-on-k8s-operator/issues/156
> Feature: Add pod affinity to FlinkCluster CRD

- controllers/flinkcluster/flinkcluster_updater.go
the submitter pod maybe deleted by kubernetes garbage collector. Then it stays as -1. Use job.Status in this case
> set submitter exit code if pod is deleted

- controllers/flinkcluster/flinkcluster_util.go
> Fix: update cluster on scale up
